'use strict';
// Sources of the pictures in the game (Wikimedia Commons). Generated by the art tools.
const CREDITS = [
 {
  "use": "Wedding scene",
  "title": "Wedding of Timurid Princes",
  "author": "",
  "date": "Early 16th-century painting (post 1501, ",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Wedding_of_Timurid_Princes.png"
 },
 {
  "use": "Coronation scene; portrait of Amir Temur",
  "title": "Depiction of Timur granting audience on the occasion of his accession, in the near contemporary Zafarnama (1424-1428), 1467 edition",
  "author": "Attributed to Bihzād (15th century)",
  "date": "2023-03-04",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Depiction_of_Timur_granting_audience_on_the_occasion_of_his_accession,_in_the_near_contemporary_Zafarnama_(1424-1428),_1467_edition.jpg"
 },
 {
  "use": "Portrait of Shah Rukh",
  "title": "Contemporary portrait of Shah Rukh (1377-1447) commissioned by his son Ibrahim Sultan in the 1436 Zafarnama, showing Shah Rukh entering Samarkand as the new Governor in 1394",
  "author": "1436 painting",
  "date": "1436-12-31",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Contemporary_portrait_of_Shah_Rukh_(1377-1447)_commissioned_by_his_son_Ibrahim_Sultan_in_the_1436_Zafarnama,_showing_Shah_Rukh_entering_Samarkand_as_the_new_Governor_in_1394.jpg"
 },
 {
  "use": "Portrait of Ulugh Beg",
  "title": "Ulugh Beg, Timurid painting 1425-50",
  "author": "",
  "date": "between 1425 and 1450date QS:P571,+1450-",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Ulugh_Beg,_Timurid_painting_1425-50.jpg"
 },
 {
  "use": "Portrait of Miran Shah",
  "title": "Young Prince Miran Shah. Zafarnama 1436",
  "author": "1435-26 artist",
  "date": "1436-12-31",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Young_Prince_Miran_Shah._Zafarnama_1436.jpg"
 },
 {
  "use": "Portrait of Umar Shaikh Mirza",
  "title": "Umar Shaykh (portrait), in the attack on Urgench in 1379. Garrett Zafarnama, painted in 1480",
  "author": "circa 1480 artist, Herat",
  "date": "1480",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Umar_Shaykh_(portrait),_in_the_attack_on_Urgench_in_1379._Garrett_Zafarnama,_painted_in_1480.jpg"
 },
 {
  "use": "Portrait of Sayf al-Din Nuküz",
  "title": "Haji Sayf al-Din (left) fighting against Timur (right). Zafarnama of 1436",
  "author": "1436 painting",
  "date": "1436-12-31",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Haji_Sayf_al-Din_(left)_fighting_against_Timur_(right)._Zafarnama_of_1436.jpg"
 },
 {
  "use": "Portrait of Toqtaqiya",
  "title": "Chingiz Oghlan, A Jochid prince at the Timurid court of Khalil Sultan in Samarkand in 1405-1406",
  "author": "1405-1406 artist",
  "date": "1405-1406",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Chingiz_Oghlan,_A_Jochid_prince_at_the_Timurid_court_of_Khalil_Sultan_in_Samarkand_in_1405-1406.jpg"
 },
 {
  "use": "Court figures",
  "title": "Timur in his yurt. Zafarnama 1436",
  "author": "1436 painting",
  "date": "1436-12-31",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Timur_in_his_yurt._Zafarnama_1436.jpg"
 },
 {
  "use": "Portrait of Toqtamish",
  "title": "Battle between Timur and Toqtamish Khan in 1391. Zafarnama of 1436 (Toqtamish detail)",
  "author": "1436 painter",
  "date": "1436-12-31",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Battle_between_Timur_and_Toqtamish_Khan_in_1391._Zafarnama_of_1436_(Toqtamish_detail).jpg"
 },
 {
  "use": "Portrait of Hafez",
  "title": "Hafez at the court of Shah Mansur (cropped)",
  "author": "Shams al-Dīn Muḥammad Ḥāfiz al-Shīrāzī",
  "date": "",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Hafez_at_the_court_of_Shah_Mansur_(cropped).jpg"
 },
 {
  "use": "Portrait of Saray Mulk Khanum",
  "title": "Timur's Empress, Saray Mulk Khanum in 1387, visiting Timur in camp. Zafarnama of 1435-36",
  "author": "1435-36 artist",
  "date": "2024-12-07",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Timur%27s_Empress,_Saray_Mulk_Khanum_in_1387,_visiting_Timur_in_camp._Zafarnama_of_1435-36.jpg"
 },
 {
  "use": "Court figures",
  "title": "Timur and his court, Zafarnama 1486, Topkapi 1964",
  "author": "15th century artist",
  "date": "15th century",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Timur_and_his_court,_Zafarnama_1486,_Topkapi_1964.jpg"
 },
 {
  "use": "Court figures and ladies",
  "title": "Ulugh Beg with ladies of his harem and retainers, Timurid 1425-50",
  "author": "",
  "date": "between 1425 and 1450date QS:P571,+1450-",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Ulugh_Beg_with_ladies_of_his_harem_and_retainers,_Timurid_1425-50.jpg"
 },
 {
  "use": "Conquest scene",
  "title": "Capture of a castle by the Timurid army (detail). Zafarnama, mid-16th century (Gulistan Palace, MS 2178)",
  "author": "1528 artist",
  "date": "1528",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Capture_of_a_castle_by_the_Timurid_army_(detail)._Zafarnama,_mid-16th_century_(Gulistan_Palace,_MS_2178).jpg"
 },
 {
  "use": "Birth scene",
  "title": "Bishan Das. The Birth of Prince, ca 1610-15, Page from Jahangirnama, Museum of Fine Arts, Boston",
  "author": "Bishandas",
  "date": "Circa 1620",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Bishan_Das._The_Birth_of_Prince,_ca_1610-15,_Page_from_Jahangirnama,_Museum_of_Fine_Arts,_Boston.jpg"
 },
 {
  "use": "Portrait of Kamal Khujandi",
  "title": "File-0111Navoii",
  "author": "",
  "date": "15th centurydate QS:P,+1450-00-00T00:00:",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:File-0111Navoii.jpeg"
 },
 {
  "use": "Portrait of Nizam al-Din Shami",
  "title": "Hatifi",
  "author": "Attributed to Kamāl ud-Dīn Behzād",
  "date": "circa 1511date QS:P571,+1511-00-00T00:00",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Hatifi.jpg"
 },
 {
  "use": "Portrait of Baha al-Din Naqshband",
  "title": "Portrait of a Dervish, Present-day Uzbekistan, Bukhara, 16th century",
  "author": "",
  "date": "16th centurydate QS:P571,+1550-00-00T00:",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Portrait_of_a_Dervish,_Present-day_Uzbekistan,_Bukhara,_16th_century.jpg"
 },
 {
  "use": "Portrait of the Ming envoy",
  "title": "Portrait of an elderly unidentified civil official",
  "author": "anonymous",
  "date": "Late 16th century",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Portrait_of_an_elderly_unidentified_civil_official.jpg"
 },
 {
  "use": "Portrait of Ghiyath al-Din Pir Ali",
  "title": "Ibrahim Sultan holding court in his throne-room. Bodleian Library MS. Ouseley Add. 176 f.239b (Ibrahim Sultan detail)",
  "author": "1425 painter",
  "date": "1425-12-31",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Ibrahim_Sultan_holding_court_in_his_throne-room._Bodleian_Library_MS._Ouseley_Add._176_f.239b_(Ibrahim_Sultan_detail).jpg"
 },
 {
  "use": "Portrait of Edigu",
  "title": "Ajashiri, at the court of Khalil Sultan in 1405-1406",
  "author": "1405-1406 artist",
  "date": "between 1405 and 1406date QS:P,+1405-00-",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Ajashiri,_at_the_court_of_Khalil_Sultan_in_1405-1406.jpg"
 },
 {
  "use": "Portrait of Muhammad-Sultan",
  "title": "Contemporary portrait of Timurid ruler Muhammad Juki on horse, 1440-45",
  "author": "1440-45 artist, British Library Shahnama Ms 239, folio 270r",
  "date": "1440",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Contemporary_portrait_of_Timurid_ruler_Muhammad_Juki_on_horse,_1440-45.jpg"
 },
 {
  "use": "Portrait of Clavijo and the Genoese",
  "title": "Portrait of a Man in a Turban (Jan van Eyck)",
  "author": "Jan van Eyck",
  "date": "1433",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Portrait_of_a_Man_in_a_Turban_(Jan_van_Eyck).jpg"
 },
 {
  "use": "Title screen",
  "title": "Gorskii 03978u",
  "author": "Sergei Prokudin-Gorskii",
  "date": "between 1905 and 1915date QS:P,+1950-00-",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Gorskii_03978u.jpg"
 },
 {
  "use": "Afrasiyab",
  "title": "Afrasiab - details from The Ambassadors' Painting 3 - great procession",
  "author": "anonymous",
  "date": "(dated ca. 650) ; 2012-04-15 11:59:07",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Afrasiab_-_details_from_The_Ambassadors%27_Painting_3_-_great_procession.JPG"
 },
 {
  "use": "Samanid Mausoleum",
  "title": "UZ Bukhara Samanid-mausoleum",
  "author": "Apfel51",
  "date": "2012-05-08",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:UZ_Bukhara_Samanid-mausoleum.jpg"
 },
 {
  "use": "Iron Gate (a gorge of the Kugitang range nearby)",
  "title": "Rocky gorge and cliffs of Kuhitang Ridge",
  "author": "Panpanchik",
  "date": "2026-05-03 21:31:46",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Rocky_gorge_and_cliffs_of_Kuhitang_Ridge.jpg"
 },
 {
  "use": "Heavenly horses",
  "title": "Horses alpine meadow Kyrgyzstan",
  "author": "Peretz Partensky from San Francisco, USA",
  "date": "2009-09-26 11:23",
  "license": "CC BY-SA 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Horses_alpine_meadow_Kyrgyzstan.jpg"
 },
 {
  "use": "Issyk-Kul",
  "title": "Issyk-Kul, Kyrgyzstan (42812885110)",
  "author": "Ninara from Helsinki, Finland",
  "date": "2018-07-18 08:09",
  "license": "CC BY 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Issyk-Kul,_Kyrgyzstan_(42812885110).jpg"
 },
 {
  "use": "Tash Rabat",
  "title": "Tash Rabat in mountains",
  "author": "Firespeaker",
  "date": "2008-03-22",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Tash_Rabat_in_mountains.jpg"
 },
 {
  "use": "Jade rivers of Khotan",
  "title": "Malikwat Yulongkashi Hotan Xinjiang China 新疆 和田 玉龙河 - panoramio (1)",
  "author": "Hiroki Ogawa",
  "date": "11 November 2015 (original upload date)",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Malikwat_Yulongkashi_Hotan_Xinjiang_China_%E6%96%B0%E7%96%86_%E5%92%8C%E7%94%B0_%E7%8E%89%E9%BE%99%E6%B2%B3_-_panoramio_(1).jpg"
 },
 {
  "use": "Ulytau",
  "title": "Ulutay 2",
  "author": "AlyonaKaptyonkina",
  "date": "2024-06-08 17:05:51",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Ulutay_2.jpg"
 },
 {
  "use": "Volga sturgeon",
  "title": "Jean Pierre Moynet - Fishing the sturgeon on the Volga river Russia 1867 (engraving) - (MeisterDrucke-1473318)",
  "author": "Jean-Pierre-Moyne",
  "date": "1867",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Jean_Pierre_Moynet_-_Fishing_the_sturgeon_on_the_Volga_river_Russia_1867_(engraving)_-_(MeisterDrucke-1473318).jpg"
 },
 {
  "use": "Ayaz-Kala",
  "title": "Ayaz-Kala 02",
  "author": "Bgag",
  "date": "2023-10-05",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Ayaz-Kala_02.jpg"
 },
 {
  "use": "Bamiyan",
  "title": "Buddhas of Bamiyan D39",
  "author": "František Řiháček",
  "date": "1961-05",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Buddhas_of_Bamiyan_D39.jpg"
 },
 {
  "use": "Nishapur turquoise",
  "title": "Turquoise of Nishapur - village of Ma'dan 11",
  "author": "Sonia Sevilla",
  "date": "2014-03-24 17:47:09",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Turquoise_of_Nishapur_-_village_of_Ma%27dan_11.JPG"
 },
 {
  "use": "Sar-i Sang lapis",
  "title": "Lazuryt - Ladjuar Medam, prow. Badakshan, Afganistan.",
  "author": "Lech Darski",
  "date": "2012-12-07 13:15:55",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Lazuryt_-_Ladjuar_Medam,_prow._Badakshan,_Afganistan..jpg"
 },
 {
  "use": "Old Merv",
  "title": "SultanSanjarMausoleum1",
  "author": "Hergit",
  "date": "2011-09-16",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:SultanSanjarMausoleum1.jpg"
 },
 {
  "use": "Altai gold (Saka gold from the Issyk kurgan)",
  "title": "Issyk kurgan Flying elk with griffin",
  "author": "eggry",
  "date": "2018-12-05 19:16:50",
  "license": "CC BY-SA 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Issyk_kurgan_Flying_elk_with_griffin.jpg"
 },
 {
  "use": "Campaign map (satellite relief)",
  "title": "Whole world - land and oceans 12000",
  "author": "NASA Goddard Space Flight Center (Blue Marble)",
  "date": "2002",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Whole_world_-_land_and_oceans_12000.jpg"
 },
 {
  "use": "Battlefield ground textures",
  "title": "Mowed light green seamless healthy lawn grass turf mowed texture landscape",
  "author": "Sisters.seamless",
  "date": "2020-06-25",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Mowed_light_green_seamless_healthy_lawn_grass_turf_mowed_texture_landscape.jpg"
 },
 {
  "use": "Battlefield sand texture",
  "title": "Smooth clean beach shore sand seamless ground texture",
  "author": "Sisters.seamless",
  "date": "2020-06-25",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Smooth_clean_beach_shore_sand_seamless_ground_texture.jpg"
 },
 {
  "use": "Music: title screen",
  "title": "Fantasy Music - The Eternal Sands",
  "author": "Hitctrl",
  "date": "",
  "license": "CC-BY 3.0",
  "page": "https://opengameart.org/content/fantasy-music-the-eternal-sands"
 },
 {
  "use": "Music: campaign map, battle",
  "title": "Desert calmness and fighting (orchestral)",
  "author": "Dizzy Crow",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/desert-calmness-and-fighting-orchestral-141"
 },
 {
  "use": "Music: campaign map",
  "title": "Hyyoshi Arabian Style Background Music",
  "author": "Tozan",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/hyyoshi-arabian-syle-backgound-music-rpg"
 },
 {
  "use": "Music: campaign map",
  "title": "Desert theme",
  "author": "yd",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/desert-theme"
 },
 {
  "use": "Music: campaign map",
  "title": "Arabesque",
  "author": "brainiac256",
  "date": "",
  "license": "CC-BY 3.0",
  "page": "https://opengameart.org/content/arabesque"
 },
 {
  "use": "Music: battle",
  "title": "Massive Battle",
  "author": "Eldritch Grim",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/massive-battle"
 },
 {
  "use": "Music: battle",
  "title": "Drums of Dawn",
  "author": "Magnesus",
  "date": "",
  "license": "CC-BY 3.0",
  "page": "https://opengameart.org/content/drums-of-dawn"
 },
 {
  "use": "Music: weddings and births",
  "title": "Darbuka Delight",
  "author": "Adiutorium",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/darbuka-delight"
 },
 {
  "use": "Music: defeat",
  "title": "Laments of the War",
  "author": "Cethiel",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/laments-of-the-war"
 },
 {
  "use": "Music: coronation and victory",
  "title": "For the king",
  "author": "Alexandr Zhelanov",
  "date": "",
  "license": "CC-BY 4.0",
  "page": "https://opengameart.org/content/for-the-king"
 },
 {
  "use": "Sounds: sword clashes, army shout",
  "title": "20 Sword Sound Effects; Crowd Shouting Ambience",
  "author": "StarNinjas",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/20-sword-sound-effects-attacks-and-clashes"
 },
 {
  "use": "Sounds: arrows",
  "title": "Swishes Sound Pack",
  "author": "artisticdude",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/swishes-sound-pack"
 },
 {
  "use": "Sounds: coins, building",
  "title": "80 CC0 RPG SFX",
  "author": "rubberduck",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/80-cc0-rpg-sfx"
 },
 {
  "use": "Sounds: clicks",
  "title": "51 UI sound effects",
  "author": "Kenney",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/51-ui-sound-effects-buttons-switches-and-clicks"
 },
 {
  "use": "Sounds: galloping horses",
  "title": "Horse Gallop Loop",
  "author": "AntumDeluge",
  "date": "",
  "license": "CC-BY 3.0",
  "page": "https://opengameart.org/content/horse-gallop-loop"
 },
 {
  "use": "Sounds: cheering",
  "title": "Free Crowd Cheering Sounds",
  "author": "Gregor Quendel",
  "date": "",
  "license": "CC-BY 4.0",
  "page": "https://opengameart.org/content/free-crowd-cheering-sounds"
 },
 {
  "use": "Sounds: war horn",
  "title": "Their Coming (generic horn sound)",
  "author": "StumpyStrust",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/their-coming-generic-horn-sound"
 },
 {
  "use": "Sounds: fanfare",
  "title": "Classic fanfare lick",
  "author": "fvcalderan",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/classic-fanfare-lick"
 },
 {
  "use": "Sounds: fire",
  "title": "Fireplace Sound loop",
  "author": "PagDev",
  "date": "",
  "license": "CC0",
  "page": "https://opengameart.org/content/fireplace-sound-loop"
 },
 {
  "use": "Sounds: wind",
  "title": "Breeze",
  "author": "Sharm",
  "date": "",
  "license": "CC-BY 4.0",
  "page": "https://opengameart.org/content/breeze"
 }
];
