// Writes sw.js: the offline cache of every file the game needs. Run after adding or changing files:
//   node tools/build-sw.js
'use strict';
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const root = path.join(__dirname, '..');
const files = ['index.html', 'manifest.webmanifest'];
for (const dir of ['css', 'js', 'img', 'audio', 'fonts', 'icons'])
  (function walk(d) { for (const f of fs.readdirSync(path.join(root, d))) { const p = d + '/' + f; if (p === 'audio/voice') continue; if (fs.statSync(path.join(root, p)).isDirectory()) walk(p); else files.push(p); } })(dir);
// The recorded voices (audio/voice) are many: they are not downloaded up front, but kept once played
const hash = crypto.createHash('sha1');
for (const f of files) hash.update(fs.readFileSync(path.join(root, f)));
const version = hash.digest('hex').slice(0, 10);
fs.writeFileSync(path.join(root, 'sw.js'), `'use strict';
// Offline cache for Turan (generated by tools/build-sw.js). A new version replaces the old cache.
const CACHE = 'turan-${version}';
const FILES = ${JSON.stringify(files, null, 0)};
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(r => r || fetch(e.request).then(res => {
    if (res.ok && new URL(e.request.url).origin === location.origin) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)); }
    return res;
  })));
});
`);
console.log(files.length, 'files, version', version);
