// Writes sw.js: the offline cache of every file the game needs. Run after adding or changing files:
//   node tools/build-sw.js
'use strict';
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const root = path.join(__dirname, '..');
const files = ['index.html', 'manifest.webmanifest'];
for (const dir of ['css', 'js', 'img', 'audio', 'fonts', 'icons'])
  (function walk(d) { for (const f of fs.readdirSync(path.join(root, d))) { const p = d + '/' + f; if (p === 'audio/voice') continue; if (fs.statSync(path.join(root, p)).isDirectory()) walk(p); else files.push(p); } })(dir);
// The recorded voices (audio/voice) are many: they are not downloaded up front, but kept once played
const hash = crypto.createHash('sha1');
for (const f of files) hash.update(fs.readFileSync(path.join(root, f)));
const version = hash.digest('hex').slice(0, 10);
fs.writeFileSync(path.join(root, 'sw.js'), `'use strict';
// Offline cache for Turan (generated by tools/build-sw.js). A new version replaces the old cache.
const CACHE = 'turan-${version}';
const FILES = ${JSON.stringify(files, null, 0)};
// Fresh copies on install: the browser's own cache could otherwise hand an old file to a new version
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES.map(f => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
const keep = (req, res) => { if (res.ok && new URL(req.url).origin === location.origin) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); } return res; };
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  // The game's code and pages: always the newest from the network, the saved copy only when offline
  if (url.origin === location.origin && (e.request.mode === 'navigate' || /\.(html|js|css|webmanifest)$/.test(url.pathname))) {
    e.respondWith(fetch(e.request, { cache: 'no-cache' }).then(res => keep(e.request, res)).catch(() => caches.match(e.request, { ignoreSearch: true })));
    return;
  }
  // Pictures, music and fonts: the saved copy first
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(r => r || fetch(e.request).then(res => keep(e.request, res))));
});
`);
console.log(files.length, 'files, version', version);
