#!/usr/bin/env python3
"""Records the lines listed in tools/voice-lines.json with neural voices, into audio/voice/<lang>/<key>.mp3,
then writes js/voice-index.js. Lines already recorded are kept, so it can be run again after adding text.
    pip install edge-tts      (ffmpeg must be installed)
    node tools/voices.js && python3 tools/voices.py
"""
import asyncio, json, os, subprocess, sys, tempfile
import edge_tts

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
PROXY = os.environ.get('HTTPS_PROXY') or os.environ.get('https_proxy')

# Who speaks: voice, speed and pitch for each role and language
CAST = {
    'narrator': {'en': ('en-GB-RyanNeural', '-8%', '-3Hz'), 'uz': ('uz-UZ-SardorNeural', '-10%', '-4Hz'),
                 'ru': ('ru-RU-DmitryNeural', '-8%', '-4Hz'), 'tr': ('tr-TR-AhmetNeural', '-8%', '-4Hz')},
    'temur':    {'en': ('en-GB-ThomasNeural', '-14%', '-10Hz'), 'uz': ('uz-UZ-SardorNeural', '-16%', '-15Hz'),
                 'ru': ('ru-RU-DmitryNeural', '-14%', '-14Hz'), 'tr': ('tr-TR-AhmetNeural', '-14%', '-14Hz')},
    'ruler':    {'en': ('en-US-ChristopherNeural', '-8%', '-6Hz'), 'uz': ('uz-UZ-SardorNeural', '-6%', '-9Hz'),
                 'ru': ('ru-RU-DmitryNeural', '-4%', '-9Hz'), 'tr': ('tr-TR-AhmetNeural', '-4%', '-9Hz')},
    'queen':    {'en': ('en-GB-SoniaNeural', '-6%', '+0Hz'), 'uz': ('uz-UZ-MadinaNeural', '-6%', '+0Hz'),
                 'ru': ('ru-RU-SvetlanaNeural', '-6%', '+0Hz'), 'tr': ('tr-TR-EmelNeural', '-6%', '+0Hz')},
}
# A palace hall around the voice; rulers stand in a bigger one
ROOM = {
    'narrator': 'highpass=f=70,lowpass=f=9500,aecho=0.8:0.55:50|95:0.18|0.10',
    'temur': 'highpass=f=60,lowpass=f=9000,bass=g=3:f=120,aecho=0.8:0.6:70|130:0.28|0.16',
    'ruler': 'highpass=f=60,lowpass=f=9000,bass=g=2:f=120,aecho=0.8:0.6:65|120:0.24|0.14',
    'queen': 'highpass=f=90,lowpass=f=10000,aecho=0.8:0.55:55|100:0.18|0.10',
}


async def record(line, sem, done, fails):
    out = os.path.join(ROOT, 'audio', 'voice', line['lang'], line['key'] + '.mp3')
    if os.path.exists(out) and os.path.getsize(out) > 0:
        done.append(line); return
    voice, rate, pitch = CAST[line['role']][line['lang']]
    async with sem:
        for attempt in range(4):
            try:
                with tempfile.NamedTemporaryFile(suffix='.mp3', delete=False) as tmp:
                    raw = tmp.name
                await edge_tts.Communicate(line['text'], voice, rate=rate, pitch=pitch, proxy=PROXY).save(raw)
                if os.path.getsize(raw) == 0: raise RuntimeError('empty')
                proc = await asyncio.create_subprocess_exec('ffmpeg', '-y', '-loglevel', 'error', '-i', raw, '-af',
                    ROOM[line['role']] + ',volume=1.5,apad=pad_dur=0.25', '-ac', '1', '-ar', '24000', '-b:a', '40k', out)
                await proc.wait()
                os.unlink(raw)
                if proc.returncode == 0 and os.path.getsize(out) > 0:
                    done.append(line); return
            except Exception as e:  # network hiccups: wait and try again
                err = e
                await asyncio.sleep(1.5 * (attempt + 1))
        fails.append(line)


async def main():
    lines = json.load(open(os.path.join(ROOT, 'tools', 'voice-lines.json'), encoding='utf8'))
    for lang in {l['lang'] for l in lines}: os.makedirs(os.path.join(ROOT, 'audio', 'voice', lang), exist_ok=True)
    sem, done, fails = asyncio.Semaphore(8), [], []
    tasks = [record(l, sem, done, fails) for l in lines]
    for i in range(0, len(tasks), 100):
        await asyncio.gather(*tasks[i:i + 100])
        print(f'{len(done)} recorded, {len(fails)} failed', flush=True)
    # The index of what exists
    have = {}
    for lang in sorted({l['lang'] for l in lines}):
        d = os.path.join(ROOT, 'audio', 'voice', lang)
        wanted = {l['key'] for l in lines if l['lang'] == lang}
        have[lang] = ' '.join(sorted(k[:-4] for k in os.listdir(d) if k.endswith('.mp3') and k[:-4] in wanted))
    with open(os.path.join(ROOT, 'js', 'voice-index.js'), 'w', encoding='utf8') as f:
        f.write("'use strict';\n// Sentences recorded by the voices (generated by tools/voices.py): fingerprints per language\n")
        f.write('const VOICE_INDEX = ' + json.dumps(have, ensure_ascii=False) + ';\n')
    if fails: print('failed:', [f['text'][:40] for f in fails[:10]]); sys.exit(1)


asyncio.run(main())
